#! /bin/sh

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &
zsh -ic "polybar_start" &
comfortable-swipe start &
bluetoothctl power on &

# Monitors
xrandr --addmode HDMI-1 1920x1080
xrandr --addmode eDP-1 1920x1080

# Wallpaper
feh --bg-fill /home/Centurion/Documents/Assets/Backgrounds/COSMOS_YELLOW_DARK.jpg &

# Workspaces
bspc monitor eDP-1 -d I II III IV V VI VII VIII IX X

# Others
bspc config pointer_follows_focus true
bspc config border_width         2
bspc config window_gap           8
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
